tasks:
  - init: |
      cargo build --target wasm32-unknown-unknown
    command: |
      cargo run --target wasm32-unknown-unknown
vscode:
  extensions:
    - matklad.rust-analyzer
    - bungcip.better-toml
    - streetsidesoftware.code-spell-checker
    - serayuzgur.crates
image:
  file: .gitpod.Dockerfile