tasks:
  - init: |
      rustup target install wasm32-unknown-unknown &&
      cargo install wasm-server-runner &&
      cargo build
    command: |
      cargo run --target wasm32-unknown-unknown &&
      wasm-bindgen --out-dir ./out/ --target web ./target/
vscode:
  extensions:
    - matklad.rust-analyzer
    - rust-lang.rust
    - bungcip.better-toml
    - streetsidesoftware.code-spell-checker
    - serayuzgur.crates